
import Foundation
import Structures
import CoreML


typealias AEClassifierValue = String

class Learning {

    /**
     AEClassifier is a model trained with csv data built on MacOS.
     to review and experiment with this dataset access the specific MacOS
     playground file.
     */
    
    func AEPredict(using statement: String) -> String? {

        guard let model = loadModel() else {
            print("model not correctly loaded..")
            return nil
        }

        //class generated by Xcode
        let modelInput = AEClassifierInput(text: statement)
        
        
        guard let prediction = try? model.prediction(from: modelInput) else {
            fatalError("Unexpected runtime error.")
        }
        
        
        let results = prediction.featureValue(for: "label")?.stringValue
        
        
        //return predicted value - String
        return results

    }



    func loadModel() -> MLModel? {
        let newModel = try? AEClassifier(configuration: MLModelConfiguration()).model
        return newModel
    }
        
}

