
import PlaygroundSupport
import Foundation
import Structures
import CoreML

/**
 `AEClassifier` is a model trained with csv data built on MacOS.
 to review and experiment with this dataset access the specific MacOS
 playground file.
*/


typealias AEClassifierResult = String

class Learning {
    
    /*
    note: AEClassifier is a model trained with csv data built on MacOS.
    to review and experiment with this dataset access the specific MacOS
    playground file.
    */

    
    func AEPredict(using statement: String) -> String? {

        guard let model = loadModel() else {
            print("model not correctly loaded..")
            return nil
        }
    
        //class generated by Xcode
        let modelInput = AEClassifierInput(text: statement)
        
        
        guard let prediction = try? model.prediction(from: modelInput) else {
            fatalError("Unexpected runtime error.")
        }
        
        let results = prediction as? AEClassifierOutput
        
        //return predicted value - String
        return results?.label

    }


    
    func loadModel() -> MLModel? {
        let newModel = try? AEClassifier(configuration: MLModelConfiguration()).model
        return newModel
    }
        
}

