//
//  SharedLink.swift
//  
//
//  Created by Wayne Bishop on 2/18/21.
//

import Foundation

/*
 note: provides the connection between public links
 generated by private users. using this convention, different
 users can generate unique links for the same url.
 */

public class SharedLink : Hashable {
    
    var short: Link // bit.ly/87
    var long: String //"www.superlong.com"
    var analytics = Array<String>() //stores a list of actions

   public init(_ short: Link, _ long: String) {
        self.short = short
        self.long = long
    }
   
    
   //records the shared link action
   public func action(_ type: String) {
        self.analytics.append(type)
    }
    
    
    //hashable conformance
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.short)
    }
    
    
    //equatable conformance
    public static func == (lhs: SharedLink, rhs: SharedLink) -> Bool {
        return (lhs.short == rhs.short)
    }
    
}
